[project]
name = "videoalchemy"
version = "0.1.0"
description = ""
authors = [
    {name = "Mohammad Hossein Gerami",email = "hsn.gerami@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material (>=9.6.20,<10.0.0)",
    "mkdocs-material-extensions (>=1.3.1,<2.0.0)",
    "mkdocs-git-revision-date-localized-plugin (>=1.4.7,<2.0.0)",
    "mkdocs (>=1.6.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
